# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b07718992fef854b04106456cec0cf8c9696a14da47d31b72b7a468cc3927c1a122ae11c3bf32e8ec7e042723e53ba558e1c01b07d5d0cc191626a7405da5c2

test:
  secret_key_base: bc9163d277fb814852e8e9f2dc0bd1a79aba835666417ad2e4bf2546f42b79179a90eb59935e458bbe3c40de1651ad8778606809b826ed789ebccc4100e78ecd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
